language: node_js
node_js:
- '8'
notifications:
  email: false
before_script:
  - 'yarn lint'
  - 'yarn size'
deploy:
  provider: npm
  email: dev@launchpadlab.com
  api_key:
    secure: XkdE/LmydCEZUY+SoMW4I2+ZY9QIzjBnA1PXdJeZ9tbx18rljfYP5aUCz5bKqP49/iA762fvi5rR3agfyQObtspDKIknMxIFFhERHPc+7H4o3H1WxUjdq++Ye1+0SklyQ0msv0cvJVmGXUUxkW03bV2v0lw/dzsxEVDyrj+KLfJ8p1vIuEO1SJrl1fQDH6h9KsTqGtrspd80RRZ/Jr/2+xYTUesPiyi5E7K7xeDRcpPm12WtUyBTQeZPeUQ8RkXinBo+9qXLS/5Zg7Id9t1u8OpQTihqcbZqGsgsEV5C0aQ+e1C3TjONl5slad8/gNdtVUnXH/dV8vcKIjJ4WltV2Pg9dSapdRS9OKg/azuY3lSXHpA/zW/C6IBkIPsaYygImbUO6inicEzqsyIXNs+ddhFZBE/efOXkXEhtBUQKRI9gRczG/1nfD695aIewgzbVhMW+miWMQvUuLXTSC6HjS7nWPbGjHaNm00GpfR1qnUauI6OPYDTp3MrFhdvSUOMPykAyFzhzBjTx8FjwDBRHMy64xvSgv+8zi/GJm/NxrEl40O4Yh9P4fH2OhK5ev+MndFiXrXZuVvjUGPIhVCvvPcfEeLEMvMZ6v5K3nOr+afKgt/XkxyoSLXVKlKAaMmXG46TDYgqLSwqn3IgVxhhd54UkK3w1Lj0Evo2yPNEMXvg=
  on:
    branch: master
  skip_cleanup: true
